### ISSUE TITLE
Installing dotnet-ef fails on Azure Pipelines builds

### ISSUE THREAD

**Issue by dannyyy** [pekspro/EF-Migrations-Script-Generator-Task#12]
Trying to install the necessary tools will fail because the tooling is just available after a session restart.

```
Starting: Generate Migration Script
==============================================================================
Task         : Entity Framework Core Migrations Script Generator
Description  : Tool for projects that use Entity Framework Core Code-First. Generates migration scripts which can be used to update a database (for instance with the task 'Azure SQL Database Deployment').
Version      : 0.0.30
Author       : PEK's Productions
Help         : [More Information](https://github.com/pekspro/EF-Migrations-Script-Generator-Task)
==============================================================================
Project path: /home/vsts/work/1/s/MyProject.Model
Start-up project path: /home/vsts/work/1/s/MyProject/MyProject.WebUI
Target folder: /home/vsts/work/1/a/migrations
Number of database contexts: 1
Checking of dotnet-ef is installed.
/usr/bin/dotnet tool list --global
Package Id      Version      Commands
-------------------------------------

Installing dotnet-ef as global tool.
/usr/bin/dotnet tool install --global dotnet-ef
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0') was successfully installed.

Generating migration script for DbCon in project /home/vsts/work/1/s/MyProject/MyProject.Model
/usr/bin/dotnet ef migrations script --idempotent --project /home/vsts/work/1/s/MyProject/MyProject.Model --startup-project /home/vsts/work/1/s/MyProject/MyProject.WebUI --output /home/vsts/work/1/a/migrations/DbCon.sql --context DbCon --verbose
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

##[error]The process '/usr/bin/dotnet' failed with exit code 1
Finishing: Generate Migration Script

```

**Comment by pekspro** [comment]
That's interesting, I haven't seen this before:

    Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.

What kind of agent are you using for building? Also, are you doing some manual installation of .NET Core SDK earlier in the pipeline?

**Comment by dannyyy** [comment]
I'm using the Azure hosted 'ubuntu-latest' image.

Prior to this task I have some dotnet restore, build and test tasks. I'm using .NET 3.0 but without using a .NET Core SDK task in the pipeline.

In the mean time I tried to split the installation and the generation. Without sucess
1. DotNetCore task to install the tool
2. Your task to generate the script

```
Starting: Install dotnet ef
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.158.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/usr/bin/dotnet tool install -g --configfile NuGet_Only.conf dotnet-ef
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.0.0') was successfully installed.
Finishing: Install dotnet ef
```

```
Starting: Generate Migration Script
==============================================================================
Task         : Entity Framework Core Migrations Script Generator
Description  : Tool for projects that use Entity Framework Core Code-First. Generates migration scripts which can be used to update a database (for instance with the task 'Azure SQL Database Deployment').
Version      : 0.0.30
Author       : PEK's Productions
Help         : [More Information](https://github.com/pekspro/EF-Migrations-Script-Generator-Task)
==============================================================================
Project path: /home/vsts/work/1/s/MyProject/MyProject.Model
Start-up project path: /home/vsts/work/1/s/MyProject/MyProject.WebUI
Target folder: /home/vsts/work/1/a/migrations
Number of database contexts: 1
Checking of dotnet-ef is installed.
/usr/bin/dotnet tool list --global
Package Id      Version      Commands 
--------------------------------------
dotnet-ef       3.0.0        dotnet-ef

dotnet-ef is already installed.
Generating migration script for DbCon in project /home/vsts/work/1/s/MyProject/MeProject.Model
/usr/bin/dotnet ef migrations script --idempotent --project /home/vsts/work/1/s/MyProject/MyProject.Model --startup-project /home/vsts/work/1/s/MyProject/MyProject.WebUI --output /home/vsts/work/1/a/migrations/DbCon.sql --context DbCon --verbose
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

##[error]The process '/usr/bin/dotnet' failed with exit code 1
Finishing: Generate Migration Script
```

My next try is to put an `source .bashrc` in between. Maybe this helps to reload the session.

Then I have another request (will open a new issue for that later):  
Since my `NuGet.config` contains some private repositories with authentication, your task is not able to run smoothly. Either I have to disable all my private repositories and enable again after your task. Or the suggested solution, that your task will allow to specify a `NuGet.config` file. Then `dotnet tool install` provides the argument `--configfile`.

Thank you very much.

**Comment by dannyyy** [comment]
I have found a solution. Using `windows-2019` is working as expected.
If you offer the possibility to use another `--configfile Nuget.Config` then I can get rid of the first of these two tasks.

```
          - task: DotNetCoreCLI@2
            displayName: "Install dotnet ef"
            inputs:
              command: custom
              custom: tool
              arguments: install -g --configfile NuGet_Only.conf dotnet-ef
          - task: pekspro.pekspro-efcore-migration-script-generator.efcore-migration-script-generator.efcore-migration-script-generator-task@0
            displayName: 'Generate Migration Script'
            #condition: and(always(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
            inputs:
              projectpath: tpc.eMedia.MyProject/tpc.eMedia.MyProject.Model
              databasecontexts: DbCon
              startupprojectpath: tpc.eMedia.MyProject/tpc.eMedia.MyProject.WebUI
              installdependencies: false
```
