### ISSUE TITLE
EF Migrations Script failing in Azure Pipeline

### ISSUE THREAD

**Issue by LearningCurvePanda** [pekspro/EF-Migrations-Script-Generator-Task#26]
I'm trying to use ef migration script in an Azure pipeline and am also receiving the dotnet-ef migrations script does not exist error. yaml code as follows:

```
- task: UseDotNet@2
      displayName: "Install .NET SDK"
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    
    - task: DotNetCoreCLI@2
      displayName: "Install dotnet-ef"
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef'

    - task: DotNetCoreCLI@2
      displayName: "Create Migration Script (Idempotent)"
      inputs:
        command: 'custom'
        projects: '$(System.DefaultWorkingDirectory)/EFDatabase/*.csproj'
        custom: 'ef migrations script'
        arguments: '--context $(dbContext) --idempotent --output $(Build.ArtifactStagingDirectory)\migration.sql'
```
