### ISSUE TITLE
Selective migrations

### ISSUE THREAD

**Issue by danielferecatu** [pekspro/EF-Migrations-Script-Generator-Task#30]
Is it in the plan to support selective migrations?

Example:
``` yml
- task: efcore-migration-script-generator-task@0
  inputs:
    projectpath:        "./path"
    databasecontexts:   "Context"
    startupprojectpath: "./startup"
    targetfolder:       "./target"
    from: "20210405144817_Migration10"     <- here
    to:   "20210405204343_Migration12"     <- here
``` 

The dotnet tool has already support for this: https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-script
